fix pbcopy/paste slowdowns due to bad pbproxy code

diff --git a/pbproxy b/pbproxy
--- a/pbproxy
+++ b/pbproxy
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 
-main() {
-
+lemonader() (
     if quiet which lemonade && quiet timeout 1 lemonade paste; then
             case "$SCRIPT_NAME" in 
                 pbcopy|*copy*)
@@ -12,32 +11,42 @@ main() {
                     ;;
             esac
     fi
+)
 
+main() {
+
+    # # right now lemonader is broken because lemonade itself also calls
+    # # pbcopy, so it recurses and goes really slow
+    # lemonader &
 
     if [[ "$CUR_PLATFORM" == "Darwin" ]]; then
     # if true; then
 
-        # on OS X we want to use the system pbcopy/pbpaste, so iterate down the 
-        # output of `which -a` to access the version of pbcopy/pbpaste that's masked
-        # by this script, and then execute it directly
-        dirs_to_try=( 
-            $(which -a "$SCRIPT_NAME" | while read i; do echo "$(dirname "$i")"; done)
-        )
+        # # on OS X we want to use the system pbcopy/pbpaste, so iterate down the 
+        # # output of `which -a` to access the version of pbcopy/pbpaste that's masked
+        # # by this script, and then execute it directly
+        # dirs_to_try=( 
+        #     $(which -a "$SCRIPT_NAME" | while read i; do echo "$(dirname "$i")"; done)
+        # )
+        #
+        # for dir in "${dirs_to_try[@]}"; do 
+        #     if [[ "$dir" == "$SCRIPT_DIR" ]]; then 
+        #         continue 
+        #     fi
+        #     break
+        # done
+        #
+        # if [[ "$dir/$SCRIPT_NAME" == "$SCRIPT_DIR/$SCRIPT_NAME" ]]; then
+        #     echo "ERROR: couldn't find system pbpaste and refusing to re-run $SCRIPT_DIR/$SCRIPT_NAME!" 
+        #     exit 1
+        # fi
+        #
+        # # execute the last item we found in path
+        # exec "$dir"/$SCRIPT_NAME
 
-        for dir in "${dirs_to_try[@]}"; do 
-            if [[ "$dir" == "$SCRIPT_DIR" ]]; then 
-                continue 
-            fi
-            break
-        done
+        # run the system pbcopy/pbpaste
+        cat | exec "/usr/bin/$SCRIPT_NAME"
 
-        if [[ "$dir/$SCRIPT_NAME" == "$SCRIPT_DIR/$SCRIPT_NAME" ]]; then
-            echo "ERROR: couldn't find system pbpaste and refusing to re-run $SCRIPT_DIR/$SCRIPT_NAME!" 
-            exit 1
-        fi
-
-        # execute the last item we found in path
-        exec "$dir"/$SCRIPT_NAME
     elif [[ "$CUR_PLATFORM" == "Linux" ]]; then
 
         if quiet which xsel && quiet timeout 1 xsel --clipboard --output; then
